services:
  ffc-ffd-frontend-poc:
    build:
      context: .
      target: production
    image: ffc-ffd-frontend-poc
    container_name: ffc-ffd-frontend-poc
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-frontend-poc-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_HOST: ${MESSAGE_HOST}
      MESSAGE_USER: ${MESSAGE_USER}
      MESSAGE_PASSWORD: ${MESSAGE_PASSWORD}
