environment: development
environmentCode:
name: ffc-ffd-frontend-poc
namespace: fcp-ffd
workstream: fcp-ffd
image: ffc-ffd-frontend-poc

labels:
  component: web

appInsights:
  connectionString:

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
